#ifndef _WIN_USER_SETTINGS_MULTITHREAD_H_
#define _WIN_USER_SETTINGS_MULTITHREAD_H_

#undef SINGLE_THREADED

#undef WOLFSSL_RW_THREADED
#define WOLFSSL_RW_THREADED

#endif /* _WIN_USER_SETTINGS_MULTITHREAD_H_ */
