#ifndef _WIN_USER_SETTINGS_H_
#define _WIN_USER_SETTINGS_H_

#undef WOLFSSL_AESNI

#undef HAVE_INTEL_RDSEED

#undef USE_INTEL_SPEEDUP

#undef WOLFSSL_AARCH64_BUILD
#define WOLFSSL_AARCH64_BUILD

#endif /* _WIN_USER_SETTINGS_H_ */
