#ifndef _WIN_USER_SETTINGS_H_
#define _WIN_USER_SETTINGS_H_

#undef WOLFSSL_AESNI

#undef HAVE_INTEL_RDSEED

#undef USE_INTEL_SPEEDUP

#undef WOLFSSL_X86_64_BUILD

#undef WOLFSSL_SYS_CA_CERTS
#define WOLFSSL_SYS_CA_CERTS

#undef WOLFSSL_TRUST_PEER_CERT
#define WOLFSSL_TRUST_PEER_CERT

#endif /* _WIN_USER_SETTINGS_H_ */
