= Contributor Code of Conduct
This code of conduct applies to all staff in Hong Kong and Singapore.

As contributors and maintainers of this project, and in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities.

We are committed to making participation in this project a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.



== We work together positively
As a company we pride ourselves on a positive and psychologically safe work environment that cultivates collaboration, creativity, and high quality work. Across the board, our staff members report that the people they work with is the top factor that makes ExpressVPN a great place to work, and we want it to stay that way. Our company culture values mutual respect, teamwork, and positive relationships. Everyone on the team should feel comfortable and welcome. We believe that articulating our accountabilities to one another through this code of conduct reinforces that respect and provides us with clear avenues to correct our behavior should it ever stray.

Day-to-day, positive working relationships are built through:

* Interpersonal awareness
* Authenticity
* Stress awareness and management
* Empathy and truly listening
* Communicating clearly
* Giving and receiving constructive feedback
* Learning from mistakes
* Valuing and prioritizing positive relationships.