= Contributing

Contributions are made to this repo via Issues and Pull Requests (PRs). A few general guidelines that cover both:

- To report security vulnerabilities, please see section on link:SECURITY.adoc#reporting-a-vulnerability[Reporting a vulnerability]
- Search for existing Issues and PRs before creating your own.
- We work hard to makes sure issues are handled in a timely manner but, depending on the impact, it could take a while to investigate the root cause. A friendly ping in the comment thread to the submitter or a contributor can help draw attention if your issue is blocking.

== Code of Conduct

Please refer to link:CODE_OF_CONDUCT.adoc[Code of Conduct] for details.

== Issues

Issues should be used to report problems with the library, request a new feature, or to discuss potential changes before a PR is created. When you create a new Issue, you will see a template that will guide you to provide the information we need to investigate.

If you find an Issue that addresses the problem you're having, please add your own reproduction information to the existing issue rather than creating a new one. Adding a https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/[reaction] can also help indicate to our maintainers that a particular problem is affecting more than just the reporter.

== Pull Requests

PRs to our libraries are always welcome and can be a quick way to get your fix or improvement slated for the next release. In general, PRs should:

- Only fix/add the functionality in question **OR** address wide-spread whitespace/style issues, not both
- Add unit or integration tests for fixed or changed functionality (if a test suite already exists)
- Address a single concern in the least number of changed lines as possible
- Include documentation in the repo
- Be accompanied by a complete Pull Request template (loaded automatically when a PR is created)

For changes that address core functionality or would require breaking changes (e.g. a major release), we recommend opening an Issue to discuss your proposal first. This is not required but can save time creating and reviewing changes.

In general, we follow the https://github.com/susam/gitpr["fork-and-pull" Git workflow]

. Fork the repository to your own Github account
. Clone the project to your machine
. Create a branch locally with a succinct but descriptive name
. Commit changes to the branch
. Following any formatting and testing guidelines specific to this repo
. Push changes to your fork
. Open a PR in our repository and follow the PR template so that we can efficiently review the changes.


== CLA

=== Individual

All contributions must indicate agreement to the link:EXPRESSVPN_CLA.adoc[ExpressVPN Individual Contributor License Agreement] by logging into GitHub via the CLA assistant and signing the provided CLA. The CLA assistant will automatically notify the PRs that require CLA signing.
