--- 
:mixins:
  :enabled:
    - wolfssl
    - unix
  :load_paths:
    - ceedling
    - ceedling/mixins

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: :mocks
  :use_deep_preprocessor: :mocks
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :compile_threads: 1
  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :output: helium
  :default_tasks:
    - test:all

:extension:
  :executable: .out

:release_build:
  :output: libhelium.a

:paths:
  :test:
    - +:test/**
    - -:test/support
  :include:
    - include/**
    - src/he/**
  :source:
    - src/**
  :support:
    - test/support

:defines:
  :release:
    - _FORTIFY_SOURCE=2
  :test:
    - TEST
    - WOLFSSL_DTLS
    - WOLFSSL_DTLS
    - WOLFSSL_DTLS13
    - WOLFSSL_DTLS_CH_FRAG
    - WOLFSSL_DTLS_MTU
    - HAVE_SECURE_RENEGOTIATION
    - WOLFSSL_TLS13
    - NO_PSK
    - NO_OLD_TLS
    - HAVE_ECC
    - HAVE_SNI
    - SINGLE_THREADED
    - HAVE_SUPPORTED_CURVES
    - HAVE_ENCRYPT_THEN_MAC

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :includes:
    - he.h
    - he_internal.h
    - wolfssl_testable_types.h
  :plugins:
    - :ignore
    - :callback
    - :ignore_arg
    - :expect_any_args
  :treat_as:
    uint8: HEX8
    uint16: HEX16
    uint32: UINT32
    int8: INT8
    bool: UINT8
  :treat_as_array:
    va_list: void
  :strippables:
    - WOLFSSL_API
    - WOLFSSL_LOCAL

:plugins:
  :enabled:
    - report_tests_pretty_stdout
    - module_generator
    - report_tests_raw_output_log
    - report_tests_log_factory
    - gcov
    - dependencies
    - compile_commands_json_db
