---
:mixins:              # `:mixins` section only recognized in base project configuration
  :enabled:           # `:enabled` list supports names and filepaths
    - base
    - 3rd_party_deps
    - macos_arm64
    - unix
  :load_paths:
    - ceedling
    - ceedling/mixins

:project:
  :build_root: build/

