////
Lightway Core
Copyright (C) 2021 Express VPN International Ltd.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
////
= {page-component-title}

== Overview

lightway-core is a small, multi-platform C library that provides the
foundational components of a virtual private network (VPN).

lightway-core is the technology that powers Lightway, ExpressVPN’s pioneering
new VPN protocol, built for an always-on world. It makes your VPN experience
speedier, more secure, and more reliable than ever. Designed to be light on its
feet, Lightway runs faster, uses less battery, and is easier to audit and
maintain.

== Documentation

* xref:faq.adoc[]
* xref:design_overview.adoc[]
* User Guide (Coming Soon)
* https://lightway.com/doxygen/annotated.html[API Documentation (Doxygen)]


